apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    creationTimestamp: 2018-12-18T22:32:20Z
    generation: 1
    name: asp
    annotations:
      kubernetes.io/ingress.class: nginx
    namespace: default
  spec:
    rules:
    - host: aspb2c.test.com
      http:
        paths:
        - backend:
            serviceName: asp
            servicePort: 5000
          path: /
    tls:
    - hosts:
      - aspb2c.test.com
      secretName: aspnett-secret
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
